Upgraded to version 3.3.6 of wrapper. Issue: MIRTH-1170

diff --git a/server/mirth-daemon b/server/mirth-daemon
--- a/server/mirth-daemon
+++ b/server/mirth-daemon
@@ -1,7 +1,14 @@
 #! /bin/sh
 
 #
-# Copyright (c) 1999, 2006 Tanuki Software Inc.
+# Copyright (c) 1999, 2009 Tanuki Software, Ltd.
+# http://www.tanukisoftware.com
+# All rights reserved.
+#
+# This software is the proprietary information of Tanuki Software.
+# You shall use it only in accordance with the terms of the
+# license agreement you entered into with Tanuki Software.
+# http://wrapper.tanukisoftware.org/doc/english/licenseOverview.html
 #
 # Java Service Wrapper sh script.  Suitable for starting and stopping
 #  wrapped Java applications on UNIX platforms.
@@ -9,6 +16,7 @@
 
 #-----------------------------------------------------------------------------
 # These settings can be modified to fit the needs of your application
+# Optimized for use with version 3.3.6 of the Wrapper.
 
 # Application
 APP_NAME="Mirth"
@@ -30,6 +38,19 @@ PIDDIR="."
 #  TERM signals.
 #IGNORE_SIGNALS=true
 
+# Wrapper will start the JVM asynchronously. Your application may have some
+#  initialization tasks and it may be desirable to wait a few seconds
+#  before returning.  For example, to delay the invocation of following
+#  startup scripts.  Setting WAIT_AFTER_STARTUP to a positive number will
+#  cause the start command to delay for the indicated period of time 
+#  (in seconds).
+# 
+WAIT_AFTER_STARTUP=0
+
+# If set, the status, start_msg and stop_msg commands will print out detailed
+#   state information on the Wrapper and Java processes.
+#DETAIL_STATUS=true
+
 # If specified, the Wrapper will be run as the specified user.
 # IMPORTANT - Make sure that the user has the required privileges to write
 #  the PID file and wrapper.log files.  Failure to be able to write the log
@@ -43,7 +64,20 @@ PIDDIR="."
 # The following two lines are used by the chkconfig command. Change as is
 #  appropriate for your application.  They should remain commented.
 # chkconfig: 2345 20 80
-# description: Test Wrapper Sample Application
+# description: @app.long.name@
+ 
+# Initialization block for the install_initd and remove_initd scripts used by
+#  SUSE linux distributions.
+### BEGIN INIT INFO
+# Provides: @app.name@
+# Required-Start: $local_fs $network $syslog
+# Should-Start: 
+# Required-Stop:
+# Default-Start: 2 3 4 5
+# Default-Stop: 0 1 6
+# Short-Description: @app.long.name@
+# Description: @app.description@
+### END INIT INFO
 
 # Do not modify anything beyond this point
 #-----------------------------------------------------------------------------
@@ -120,23 +154,29 @@ fi
 
 # Process ID
 ANCHORFILE="$PIDDIR/$APP_NAME.anchor"
+STATUSFILE="$PIDDIR/$APP_NAME.status"
+JAVASTATUSFILE="$PIDDIR/$APP_NAME.java.status"
 PIDFILE="$PIDDIR/$APP_NAME.pid"
 LOCKDIR="/var/lock/subsys"
 LOCKFILE="$LOCKDIR/$APP_NAME"
 pid=""
 
 # Resolve the location of the 'ps' command
-PSEXE="/usr/bin/ps"
-if [ ! -x "$PSEXE" ]
-then
-    PSEXE="/bin/ps"
+PSEXE="/usr/ucb/ps"
     if [ ! -x "$PSEXE" ]
     then
-        echo "Unable to locate 'ps'."
-        echo "Please report this message along with the location of the command on your system."
-        exit 1
+        PSEXE="/usr/bin/ps"
+        if [ ! -x "$PSEXE" ]
+        then
+            PSEXE="/bin/ps"
+            if [ ! -x "$PSEXE" ]
+            then
+                echo "Unable to locate 'ps'."
+                echo "Please report this message along with the location of the command on your system."
+                exit 1
+            fi
+        fi
     fi
-fi
 
 # Resolve the os
 DIST_OS=`uname -s | tr [:upper:] [:lower:] | tr -d [:blank:]`
@@ -145,7 +185,10 @@ case "$DIST_OS" in
         DIST_OS="solaris"
         ;;
     'hp-ux' | 'hp-ux64')
+        # HP-UX needs the XPG4 version of ps (for -o args)
         DIST_OS="hpux"
+        UNIX95=""
+        export UNIX95   
         ;;
     'darwin')
         DIST_OS="macosx"
@@ -156,31 +199,52 @@ case "$DIST_OS" in
 esac
 
 # Resolve the architecture
-DIST_ARCH=`uname -p | tr [:upper:] [:lower:] | tr -d [:blank:]`
-if [ "$DIST_ARCH" = "unknown" ]
+if [ "$DIST_OS" = "macosx" ]
 then
-    DIST_ARCH=`uname -m | tr [:upper:] [:lower:] | tr -d [:blank:]`
+    DIST_ARCH="universal"
+else
+    DIST_ARCH=
+    DIST_ARCH=`uname -p 2>/dev/null | tr [:upper:] [:lower:] | tr -d [:blank:]`
+    if [ "X$DIST_ARCH" = "X" ]
+    then
+        DIST_ARCH="unknown"
+    fi
+    if [ "$DIST_ARCH" = "unknown" ]
+    then
+        DIST_ARCH=`uname -m 2>/dev/null | tr [:upper:] [:lower:] | tr -d [:blank:]`
+    fi
+    case "$DIST_ARCH" in
+        'amd64' | 'athlon' | 'i386' | 'i486' | 'i586' | 'i686' | 'x86_64')
+            DIST_ARCH="x86"
+            ;;
+        'ia32' | 'ia64' | 'ia64n' | 'ia64w')
+            DIST_ARCH="ia"
+            ;;
+        'ip27')
+            DIST_ARCH="mips"
+            ;;
+        'power' | 'powerpc' | 'power_pc' | 'ppc64')
+            DIST_ARCH="ppc"
+            ;;
+        'pa_risc' | 'pa-risc')
+            DIST_ARCH="parisc"
+            ;;
+        'sun4u' | 'sparcv9')
+            DIST_ARCH="sparc"
+            ;;
+        '9000/800')
+            DIST_ARCH="parisc"
+            ;;
+    esac
 fi
-case "$DIST_ARCH" in
-    'amd64' | 'athlon' | 'ia32' | 'ia64' | 'i386' | 'i486' | 'i586' | 'i686' | 'x86_64')
-        DIST_ARCH="x86"
-        ;;
-    'ip27')
-        DIST_ARCH="mips"
-        ;;
-    'power' | 'powerpc' | 'power_pc' | 'ppc64')
-        DIST_ARCH="ppc"
-        ;;
-    'pa_risc' | 'pa-risc')
-        DIST_ARCH="parisc"
-        ;;
-    'sun4u' | 'sparcv9')
-        DIST_ARCH="sparc"
-        ;;
-    '9000/800')
-        DIST_ARCH="parisc"
-        ;;
-esac
+
+# OSX always places Java in the same location so we can reliably set JAVA_HOME
+if [ "$DIST_OS" = "macosx" ]
+then
+    if [ -z "$JAVA_HOME" ]; then
+        JAVA_HOME="/Library/Java/Home"; export JAVA_HOME
+    fi
+fi
 
 outputFile() {
     if [ -f "$1" ]
@@ -195,56 +259,23 @@ outputFile() {
 # If a 32-bit wrapper binary exists then it will work on 32 or 64 bit
 #  platforms, if the 64-bit binary exists then the distribution most
 #  likely wants to use long names.  Otherwise, look for the default.
-# For macosx, we also want to look for universal binaries.
 WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
 if [ -x "$WRAPPER_TEST_CMD" ]
 then
     WRAPPER_CMD="$WRAPPER_TEST_CMD"
 else
-    if [ "$DIST_OS" = "macosx" ]
+    WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
+    if [ -x "$WRAPPER_TEST_CMD" ]
     then
-        WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-32"
-        if [ -x "$WRAPPER_TEST_CMD" ]
-        then
-            WRAPPER_CMD="$WRAPPER_TEST_CMD"
-        else
-            WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-            if [ -x "$WRAPPER_TEST_CMD" ]
-            then
-                WRAPPER_CMD="$WRAPPER_TEST_CMD"
-            else
-                WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-64"
-                if [ -x "$WRAPPER_TEST_CMD" ]
-                then
-                    WRAPPER_CMD="$WRAPPER_TEST_CMD"
-                else
-                    if [ ! -x "$WRAPPER_CMD" ]
-                    then
-                        echo "Unable to locate any of the following binaries:"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-universal-32"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-universal-64"
-                        outputFile "$WRAPPER_CMD"
-                        exit 1
-                    fi
-                fi
-            fi
-        fi
+        WRAPPER_CMD="$WRAPPER_TEST_CMD"
     else
-        WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-        if [ -x "$WRAPPER_TEST_CMD" ]
+        if [ ! -x "$WRAPPER_CMD" ]
         then
-            WRAPPER_CMD="$WRAPPER_TEST_CMD"
-        else
-            if [ ! -x "$WRAPPER_CMD" ]
-            then
-                echo "Unable to locate any of the following binaries:"
-                outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
-                outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-                outputFile "$WRAPPER_CMD"
-                exit 1
-            fi
+            echo "Unable to locate any of the following binaries:"
+            outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
+            outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
+            outputFile "$WRAPPER_CMD"
+            exit 1
         fi
     fi
 fi
@@ -265,6 +296,14 @@ then
 else
    ANCHORPROP=wrapper.anchorfile=\"$ANCHORFILE\"
    IGNOREPROP=wrapper.ignore_signals=TRUE
+fi
+
+# Build the status file clause.
+if [ "X$DETAIL_STATUS" = "X" ]
+then
+   STATUSPROP=
+else
+   STATUSPROP="wrapper.statusfile=\"$STATUSFILE\" wrapper.java.statusfile=\"$JAVASTATUSFILE\""
 fi
 
 # Build the lock file clause.  Only create a lock file if the lock directory exists on this platform.
@@ -326,7 +365,15 @@ checkUser() {
 
         # Still want to change users, recurse.  This means that the user will only be
         #  prompted for a password once. Variables shifted by 1
-        su -m $RUN_AS_USER -c "\"$REALPATH\" $2"
+        # 
+        # Use "runuser" if this exists.  runuser should be used on RedHat in preference to su.
+        #
+        if test -f "/sbin/runuser"
+        then
+            /sbin/runuser - $RUN_AS_USER -c "\"$REALPATH\" $2"
+        else
+            su - $RUN_AS_USER -c "\"$REALPATH\" $2"
+        fi
 
         # Now that we are the original user again, we may need to clean up the lock file.
         if [ "X$LOCKPROP" != "X" ]
@@ -347,6 +394,7 @@ checkUser() {
 }
 
 getpid() {
+    pid=""
     if [ -f "$PIDFILE" ]
     then
         if [ -r "$PIDFILE" ]
@@ -359,7 +407,21 @@ getpid() {
                 #  common is during system startup after an unclean shutdown.
                 # The ps statement below looks for the specific wrapper command running as
                 #  the pid.  If it is not found then the pid file is considered to be stale.
-                pidtest=`$PSEXE -p $pid -o args | grep "$WRAPPER_CMD" | tail -1`
+                case "$DIST_OS" in
+                    'macosx')
+                        pidtest=`$PSEXE -ww -p $pid -o command | grep "$WRAPPER_CMD" | tail -1`
+                        ;;
+                    'solaris')
+                        pidtest=`$PSEXE -auxww  $pid | grep "$WRAPPER_CMD" | tail -1`
+                        ;;                    
+                    'hpux')
+                        pidtest=`$PSEXE -p $pid -x -o args | grep "$WRAPPER_CMD" | tail -1`
+                        ;;
+                    *)
+                        pidtest=`$PSEXE -p $pid -o args | grep "$WRAPPER_CMD" | tail -1`
+                        ;;
+                esac
+
                 if [ "X$pidtest" = "X" ]
                 then
                     # This is a stale pid file.
@@ -375,8 +437,43 @@ getpid() {
     fi
 }
 
+getstatus() {
+    STATUS=
+    if [ -f "$STATUSFILE" ]
+    then
+        if [ -r "$STATUSFILE" ]
+        then
+            STATUS=`cat "$STATUSFILE"`
+        fi
+    fi
+    if [ "X$STATUS" = "X" ]
+    then
+        STATUS="Unknown"
+    fi
+    
+    JAVASTATUS=
+    if [ -f "$JAVASTATUSFILE" ]
+    then
+        if [ -r "$JAVASTATUSFILE" ]
+        then
+            JAVASTATUS=`cat "$JAVASTATUSFILE"`
+        fi
+    fi
+    if [ "X$JAVASTATUS" = "X" ]
+    then
+        JAVASTATUS="Unknown"
+    fi
+}
+
 testpid() {
-    pid=`$PSEXE -p $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1`
+    case "$DIST_OS" in
+        'solaris')
+            pid=`$PSEXE  $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1`
+            ;;
+        *)
+            pid=`$PSEXE -p $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1`
+            ;;
+    esac
     if [ "X$pid" = "X" ]
     then
         # Process is gone so remove the pid file.
@@ -391,7 +488,7 @@ console() {
     if [ "X$pid" = "X" ]
     then
         # The string passed to eval must handles spaces in paths correctly.
-        COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=$APP_NAME wrapper.pidfile=\"$PIDFILE\" $ANCHORPROP $LOCKPROP"
+        COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=\"$APP_NAME\" wrapper.pidfile=\"$PIDFILE\" wrapper.name=\"$APP_NAME\" wrapper.displayname=\"$APP_LONG_NAME\" $ANCHORPROP $STATUSPROP $LOCKPROP"
         eval $COMMAND_LINE
     else
         echo "$APP_LONG_NAME is already running."
@@ -400,25 +497,55 @@ console() {
 }
  
 start() {
-    echo "Starting $APP_LONG_NAME..."
+    echo -n "Starting $APP_LONG_NAME..."
     getpid
     if [ "X$pid" = "X" ]
     then
         # The string passed to eval must handles spaces in paths correctly.
-        COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=$APP_NAME wrapper.pidfile=\"$PIDFILE\" wrapper.daemonize=TRUE $ANCHORPROP $IGNOREPROP $LOCKPROP"
+        COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=\"$APP_NAME\" wrapper.pidfile=\"$PIDFILE\" wrapper.name=\"$APP_NAME\" wrapper.displayname=\"$APP_LONG_NAME\" wrapper.daemonize=TRUE $ANCHORPROP $IGNOREPROP $STATUSPROP $LOCKPROP"
         eval $COMMAND_LINE
     else
         echo "$APP_LONG_NAME is already running."
         exit 1
     fi
+
+    # Sleep for a few seconds to allow for intialization if required 
+    #  then test to make sure we're still running.
+    #
+    i=0
+    while [ $i -lt $WAIT_AFTER_STARTUP ]
+    do
+        sleep 1
+        echo -n "."
+        i=`expr $i + 1`
+    done
+    if [ $WAIT_AFTER_STARTUP -gt 0 ]
+    then
+        getpid
+        if [ "X$pid" = "X" ]
+        then
+            echo " WARNING: $APP_LONG_NAME may have failed to start."
+            exit 1
+        else
+            echo " running ($pid)."
+        fi
+    else 
+        echo ""
+    fi
 }
  
 stopit() {
+    # $1 exit if down flag
+    
     echo "Stopping $APP_LONG_NAME..."
     getpid
     if [ "X$pid" = "X" ]
     then
         echo "$APP_LONG_NAME was not running."
+        if [ "X$1" = "X1" ]
+        then
+            exit 1
+        fi
     else
         if [ "X$IGNORE_SIGNALS" = "X" ]
         then
@@ -482,7 +609,13 @@ status() {
         echo "$APP_LONG_NAME is not running."
         exit 1
     else
-        echo "$APP_LONG_NAME is running ($pid)."
+        if [ "X$DETAIL_STATUS" = "X" ]
+        then
+            echo "$APP_LONG_NAME is running (PID:$pid)."
+        else
+            getstatus
+            echo "$APP_LONG_NAME is running (PID:$pid, Wrapper:$STATUS, Java:$JAVASTATUS)"
+        fi
         exit 0
     fi
 }
@@ -493,7 +626,6 @@ dump() {
     if [ "X$pid" = "X" ]
     then
         echo "$APP_LONG_NAME was not running."
-
     else
         kill -3 $pid
 
@@ -503,6 +635,40 @@ dump() {
             exit 1
         else
             echo "Dumped $APP_LONG_NAME."
+        fi
+    fi
+}
+
+# Used by HP-UX init scripts.
+startmsg() {
+    getpid
+    if [ "X$pid" = "X" ]
+    then
+        echo "Starting $APP_LONG_NAME... (Wrapper:Stopped)"
+    else
+        if [ "X$DETAIL_STATUS" = "X" ]
+        then
+            echo "Starting $APP_LONG_NAME... (Wrapper:Running)"
+        else
+            getstatus
+            echo "Starting $APP_LONG_NAME... (Wrapper:$STATUS, Java:$JAVASTATUS)"
+        fi
+    fi
+}
+
+# Used by HP-UX init scripts.
+stopmsg() {
+    getpid
+    if [ "X$pid" = "X" ]
+    then
+        echo "Stopping $APP_LONG_NAME... (Wrapper:Stopped)"
+    else
+        if [ "X$DETAIL_STATUS" = "X" ]
+        then
+            echo "Stopping $APP_LONG_NAME... (Wrapper:Running)"
+        else
+            getstatus
+            echo "Stopping $APP_LONG_NAME... (Wrapper:$STATUS, Java:$JAVASTATUS)"
         fi
     fi
 }
@@ -521,12 +687,18 @@ case "$1" in
 
     'stop')
         checkUser "" $1
-        stopit
+        stopit "0"
         ;;
 
     'restart')
         checkUser touchlock $1
-        stopit
+        stopit "0"
+        start
+        ;;
+
+    'condrestart')
+        checkUser touchlock $1
+        stopit "1"
         start
         ;;
 
@@ -540,8 +712,18 @@ case "$1" in
         dump
         ;;
 
+    'start_msg')
+        checkUser "" $1
+        startmsg
+        ;;
+
+    'stop_msg')
+        checkUser "" $1
+        stopmsg
+        ;;
+
     *)
-        echo "Usage: $0 { console | start | stop | restart | status | dump }"
+        echo "Usage: $0 { console | start | stop | restart | condrestart | status | dump }"
         exit 1
         ;;
 esac
