Added a few changes to the Linux service.

diff --git a/server/mirth-daemon b/server/mirth-daemon
--- a/server/mirth-daemon
+++ b/server/mirth-daemon
@@ -15,8 +15,8 @@ APP_NAME="Mirth"
 APP_LONG_NAME="Mirth"
 
 # Wrapper
-WRAPPER_CMD="./wrapper-x86-32bit"
-WRAPPER_CONF="../conf/wrapper.conf"
+WRAPPER_CMD="wrapper-x86-32bit"
+WRAPPER_CONF="conf/wrapper.conf"
 
 # Priority at which to run the wrapper.  See "man nice" for valid priorities.
 #  nice is only used if a priority is specified.
@@ -444,34 +444,34 @@ stopit() {
         #  actually stop as it depends on settings in wrapper.conf.
         #  Loop until it does.
         savepid=$pid
-        CNT=0
-        TOTCNT=0
-        while [ "X$pid" != "X" ]
-        do
+        #CNT=0
+        #TOTCNT=0
+        #while [ "X$pid" != "X" ]
+        #do
             # Show a waiting message every 5 seconds.
-            if [ "$CNT" -lt "5" ]
-            then
-                CNT=`expr $CNT + 1`
-            else
-                echo "Waiting for $APP_LONG_NAME to exit..."
-                CNT=0
-            fi
-            TOTCNT=`expr $TOTCNT + 1`
+        #    if [ "$CNT" -lt "5" ]
+        #    then
+        #        CNT=`expr $CNT + 1`
+        #    else
+        #        echo "Waiting for $APP_LONG_NAME to exit..."
+        #        CNT=0
+        #    fi
+        #    TOTCNT=`expr $TOTCNT + 1`
 
-            sleep 1
+        #    sleep 1
 
-            testpid
-        done
+         #   testpid
+        #done
 
         pid=$savepid
-        testpid
-        if [ "X$pid" != "X" ]
-        then
-            echo "Failed to stop $APP_LONG_NAME."
-            exit 1
-        else
+        #testpid
+        #if [ "X$pid" != "X" ]
+        #then
+        #    echo "Failed to stop $APP_LONG_NAME."
+        #    exit 1
+        #else
             echo "Stopped $APP_LONG_NAME."
-        fi
+        #fi
     fi
 }
 
